README.md

- Updates the README to include instructions for installing Ubuntu packages

updates readme with ubuntu packages

---

config/local.config
migrations/1583473459-payment_v2.sql
rebar.lock
src/be_txn.erl
src/be_txn_actor.erl

- Add support for ingestion payment_v2 txns
- Add migration for the same
- Fix local.config to use `data` dir as base_dir

Add support for payment_v2 txns

---

migrations/1585355922-txn_activity_filter.sql

This adds a stored function to reduce the `fields` for transactions to entries "related" to a given account.

Add txn activity filter

---

deb/blockchain-etl.service

Adds a resart policy to deal with crashing etl

Add more complete systemd unit

---

README.md

Need `build-essential` to build on Ubuntu. Also added note about macOS initial sync issue.

Update README with required package and macOS note

---

migrations/1591708556-block_snapshot_hash.sql
src/be_db_block.erl
src/be_db_oracle_price.erl

Indexes it for hash based lookup

Add snapshot-hash to blocks table

---

migrations/1592918856-block_created_at.sql
src/be_db_block.erl

This helps estimate block gossip time

Add created_at to blocks

---

config/sys.config
migrations/1593015009-stats_inventory.sql
src/be_db_follower.erl
src/be_db_stats.erl

Adds a stats_inventory table to update expensive/common total counts as
each block comes in

Add a stats_inventory table

---

migrations/1593644594-location_city_search.sql

Adds a search_city column to aid searching for city names

Add search_city

---

migrations/1593782722-consolidate_city_search.sql

search_city does the right thing so we'll work with that and avoid the
extra index

remove the extra search column

---

config/sys.config
migrations/1597773017-rewards.sql
src/be_db_follower.erl
src/be_db_reward.erl

Adds a rewards table that stores rewards per account/gateway a separate table for easier queries

Add rewards

---

migrations/1602607961-gateway_name.sql
src/be_cli_backfill.erl
src/be_db_backfill.erl
src/be_db_gateway.erl

----
Adds animal names and an index for these names for use by the API. This will auto populate as gateways update their state in the gateways table, but for faster results a `backfill gateway_names` is provided to backfill all existing gateways in the inventory
Fixes #100

Adds gateway animal names to inventory

---

src/be_db_stats.erl

Adds cities and countries stats to counts.
Fixes: https://github.com/helium/blockchain-http/issues/133

Add cities and countries to stats_inventory

---

migrations/1608833675-drop_gateway_score.sql
src/be_db_gateway.erl

**WARNING** This is a one way migration that removes all score data from gateways and gateway_inventory

Drop alpha/beta/delta/score from gateway(_inventory)

---

migrations/1610634227-reward_scale.sql
rebar.config
rebar.lock
src/be_db_gateway.erl

Adds reward_scale to gateways and gateway_inventory

Add reward scale to gateway/gateway_inventory

---

src/be_db_packet.erl

There's a conflict at block `455157` (and possibly blocks after it) that causes a duplicate key error due to unintended duplication within the state channel itself. This patch fixes it by ignoring duplicate packet inserts, which are currently happening within the same transaction, before the packet even hits the DB.
SQL error log:
```
2021-01-21 16:31:14 UTC:172.30.5.190(54845):postgres@etl:[19078]:ERROR: duplicate key value violates unique constraint "packets_pkey"
2021-01-21 16:31:14 UTC:172.30.5.190(54845):postgres@etl:[19078]:DETAIL: Key (block, transaction_hash, gateway)=(455157, KjTSZqdMtcWoIEnK5Ap4bqE9XWohbE2vrjs70tFWxy4, 11UYATF4cNVudfTzKzEkYnGREbaEQSdvT64wQZAvdfBTncWppmj) already exists.
2021-01-21 16:31:14 UTC:172.30.5.190(54845):postgres@etl:[19078]:STATEMENT: insert into …
```

Fix packets ingest for early state channels

---

.env.dev
.env.testnet
.gitignore
Makefile
config/sys.config
migrations/1614947350-router_actor_role.sql
migrations/1614947351-ouis.sql
src/be_cli_backfill.erl
src/be_db_backfill.erl
src/be_db_oui.erl
src/be_db_txn_actor.erl

OUIs are more than just transactions since they have a lifetime of changes. 
This adds ouis and oui_inventory like all other blockchain objects that need tracked changes over time.

Adds proper oui tables 

---

config/sys.config
migrations/1612480000-router_actor_role.sql
migrations/1612480010-ouis.sql
src/be_cli_backfill.erl
src/be_db_backfill.erl
src/be_db_follower.erl
src/be_db_oui.erl

This adds ouis and oui_inventory tables and keeps them up to date to reflect the changes that are made to oui state

Adds oui support

---

migrations/1616328011-hotspot_location_search.sql
src/be_cli_backfill.erl
src/be_db_backfill.erl
src/be_db_geocoder.erl

This adds a postgis extensioon dependency and a geometry column and index for locations.
It also adds a backfill `location_geometry` to backfill locations with their geometry information.

Adds location geo search

---

src/be_db_geocoder.erl

Fixes geocoder not handling an empty/missing google api key

---

Dockerfile
README.md
config/docker_etl.config.src
rebar.config

This pull request takes the work Evan already did on the validator to support Docker and modifies it to work for ETL.

Adds Docker Support

---

src/be_cli_backfill.erl

I know what you're thinking -- how is this guy so good? -- but rest assured I put one pant leg on at a time, just like everybody else

Fix typo in backfill usage command

---

Dockerfile

Fix rust install/build

---

Dockerfile

Adding curl for downloading the rust tool chain in the dockerfile.

Adding curl removing wget from Dockerfile

---

migrations/1621600152-gateway_mode.sql
src/be_db_gateway.erl

This allows tracking of what mode a gateway was added to the blockchain

Adds gateway_mode to gateway/inventory

---

src/be_cli_backfill.erl

Supposed to be gateway_location_hex not gateways_location_hex

Update Backfill usage mistake

---

config/sys.config
src/be_db_block.erl

To aid with snapshot desync debugging

Save bad snapshot to disk and sync to s3

---

migrations/1627043667-gateway_payer.sql
src/be_cli_backfill.erl
src/be_db_backfill.erl

And adds a trigger on inventory insert (only) to look up and update the payer for the newly added gateway.
Part of: https://github.com/helium/blockchain-http/issues/281

Adds payer to gateway_inventory

---

src/be_db_stats.erl

Adds a `hotspots_dataonly` counter to stats
Fixes: https://github.com/helium/blockchain-etl/issues/216

Adds hotspots_dataonly count to stats

---

src/be_db_pending_txn.erl

* Use txn created_at as the txn_mgr key
*  Report an error when a duplicate submission was detected
This will help identify the source of https://github.com/helium/blockchain-http/issues/324

Use created_at as the txn key

---

rebar.config
rebar.lock
src/be_db_backfill.erl
src/be_db_block.erl
src/be_txn.erl

Uses core to_json rewards_metadata lookup feature to avoid yet another rewards_metadata pass

to_json opts for rewards_metadata

---

src/be_db_backfill.erl

Thanks again for helping me fix geometry issue

Fix the tiniest of typos: part deux

---

README.md

- Discord seems preferred for support (right?)
- there are DB backups now but you should be careful about them
- thanks for all you do, marc

Add info about database snapshots and #blockchain-dev for support

---

src/be_db_block.erl

With pocv11 to_json for poc_receipts became more expensive which shows in increased be_db_block processing times. This does _not_a address the root of the performance problem but parallelizes the to_json calls for all txns in a block

use pmap for txn json construction

---

src/be_db_stats.erl

Fixes https://github.com/helium/blockchain-http/issues/392

Add hotspots_online, fix city count

---

src/be_db_txn_actor.erl
src/be_utils.erl

Break up txn_actor queries into batches of 100, 10 and single inserts to attempt to speed up large batches of actor inserts

add 100/10/1 batch value inserts

---

rebar.config
src/be_db_txn_actor.erl

Fixes https://github.com/helium/blockchain-http/issues/408

Upgrade core.. set role  for transfer_hotspot_v2

---

src/be_db_block.erl

Problem to solve: We want to write a compressed snapshot file and appropriate metadata if such a file exists.
Requires: https://github.com/helium/blockchain-core/pull/1254

Write compressed file

---

migrations/1649804744-location_geo_index.sql

Per @ci-work suggestion to speedup ST_*  queries

Add geo location index

---

src/be_db_block.erl

Companion to https://github.com/helium/blockchain-core/pull/1316

Stop publishing uncompressed file data

---

Makefile
config/devnet.config
rebar.config

Configure devnet with appropriate genesis block and sys.config

Add a devnet config; autoupdate genesis blocks
