helium/blockchain-etl

- .buildkite/Dockerfile
- .buildkite/scripts/start.sh
Problem to solve: We want to execute migrations automatically when the container starts, and then start the application
Solution: Add a `start.sh` entry point for Docker which implements this
> Add start.sh Docker entrypoint; remove Docker port

- .buildkite/hooks/pre-command
- .buildkite/scripts/make_docker.sh
- rebar.config
Problem to solve: The buildkite build is broken because relx can't find files to copy into the release directory.
Solution: Make profile specific overlay directives.
> Bump erlang to 22.1.8; fix relx overlays

- src/be_txn.erl
The `type` and `key` functions are going to be removed when [core#332](https://github.com/helium/blockchain-core/pull/332) lands.
> Remove unused functions for txn_token_burn_v1

- .buildkite/pipeline.yml
- Makefile
- config/sys.config
- rebar.config
Set dev as default profile. This will break existing prod based
installs but it looks like they were broken for makefile support anyway
Buildkite will set PROFILE to prod for the debian package build to get
the same effect we were having before
> Add make profile support.

- config/prod.config
- config/sys.config
- src/be_sup.erl
The changes in the build scripts pull in an empty .env which overrides the target installation directory. This changes the prod release to make the .env configurable and sets it to `/var/data/blockchain_etl/.env` for the prod release
> Make .env pluggable in sys.config

- migrations/1584651322-gateway_first_block.sql
- src/be_gateway.erl
This adds first_block to the gateways table and exposes it in the gateway_ledger. This will allow ordering of the ledger to remain stable (in combination with the gateway address)
> Add first_block to gateways

- config/.env
This file gets copied to the release directory on production builds and is always loaded by `psql_migration`. The current `make run` command overwrites this file if the build is on a local machine but this doesn't work for a clean checkout.
> Empty .env file

- migrations/1586300385-rebuild_first_blocks.sql
- src/be_account.erl
- src/be_gateway.erl
Rebuilds the first_block values for all accounts and gateway records
since the insertion logic was doing it wrong.
The migration resets all values to the correct one while the run-time
insertion statements are fixed to use the correct block
> Rebuild first_blocks

- migrations/1586706609-ledger_first_block.sql
- src/be_account.erl
- src/be_gateway.erl
This removes the previously added `first_block` column from `gateways` and `accounts`. They're expensive to have to recalculate on every insert. 
The materialized view for the `gateway_ledger` and `account_ledger` is modified to calculate the first_block as part of it's work removing it from the block insertion time.
In addition this also sneaks in the location for each gateway in the ledger 
This migration _will_ requires a fully stopped etl migration pass
> Move first block to materialized view

- migrations/1587049334-pending_txn_fields.sql
- src/be_pending_txn_worker.erl
The fields column is populated with the json representation of the transaction when the status of the transaction goes to pending
> Add fields column to pending_txns

- migrations/1587175755-fix_txn_filter_payment.sql
The payment_v2 transaction actor filter would take the wrong branch because we were  using the wrong json operator to extract the payer field. 
This migration fixes that oversight
> Fix payment_v2 filter for payer

- rebar.config
This fixes the migrations script which does not knwo where the system
erlang is installed.
> Add erts to dev release profile

- migrations/1588975207-state_channel_open.sql
- migrations/1588975208-state_channel_close.sql
- migrations/1588975221-state_channel_role_open.sql
- migrations/1588975222-state_channel_role_close.sql
psql migrations don't like multiple alter types in the same migration. Split them up into individual migrations.. Sorry :-/
> Move enum alters to individual migrations

- Makefile
This makes it easier to run migrations as a make target
`make migrations` will stop a running ETL application and run available database migrations. 
*Note* that you will need to `make start` to restart the application once migrations are complete
> Add a migrations make target

- migrations/1590689602-gateway_inventory.sql
- src/be_db_gateway.erl
- src/be_db_geocoder.erl
Instead of gateway_ledger as a materialized view we trigger on gateway
inserts to update a gateway_inventory table with new values.
> Move to gateway_inventory

- migrations/1590689602-gateway_inventory.sql
- migrations/1591133143-account_inventory.sql
- migrations/1591138658-state_channel_accounts.sql
- src/be_db_account.erl
- src/be_db_geocoder.erl
This switches from a materialized view for account to an
account_inventory which is updated on a trigger with newly inserted
rows for accounts.
This should make ledger recalculation time go away and, more importantly make account inventory updates more synchronized with the block that affects any account
> Account inventory

- migrations/1591282933-state_channel_counts.sql
This adds a simple migration that helps http front-ends calculate summary packet counts for state channels.
> Add state channel summary function

- src/be_db_gateway_status.erl
Relaxes the recent challenge check for hotspot status twice the poc
interval instead of just once.
> relax gateway recent challenge check

- migrations/1593015009-stats_inventory.sql
Fix for broken `stats_inventory` migration, sets default value to 0 for all stat counters on a reset or new migration.
> Set default value for counter

- migrations/1593389882-oracle_inventory.sql
- src/be_db_vars.erl
Adds an oracle_inventory table to be able to query the oracle public keys without having to decode base64 encoded values from the vars_inventory table
> Add oracle_inventory

- migrations/1593610727-location_search.sql
- src/be_db_geocoder.erl
This adds a search column to the locations table and uses a function to fill it with street/city/state/country search words which are longer than 3 characters. 
A GIN index is then used to do a fuzzy search using this search column
> Add search on geocoded location

- migrations/1594155785-gateway_status_parts.sql
- src/be_db_gateway_status.erl
This leaves the online derived column intact for now with plans for its future removal since the front ends can derive the online status from the stored values
> Break out gateway_status fields

- src/be_txn.erl
State channels allow gateways that are not added to the blockchain to transit data (they won't be rewarded for it). 
The missing gateway in the ledger was making ETL get very mad. It's happier with this fix
> Handle un-added gateway in state channel summary

- src/be_db_txn_actor.erl
This fixes the payer actor to be the owner when the payer is not defined
for the transaction
> Fix payer for add/assert

- src/be_db_gateway_status.erl
Leaves the exisitng value in place even when gossip no longer has it
since it was the last known value.
> coalesce gossip data in database

- src/be_db_gateway_status.erl
apparently when guards have a slightly weird operator precedence.. perhaps related to erlang versions?
> operator precedence fix

- src/be_db_gateway_status.erl
The COALESCE function returns the first non-NULL argument so we
were losing the new value for the old one if it wasn't NULL which
is the opposite of what we wanted.
CC: @madninja
> Switch ordering of coalesced values

- src/be_db_block.erl
- src/be_db_txn_actor.erl
We do this by ignoring conflicts on insert for transsactions and actors.
This will have some odd side effects like the block txn count being of
but these errors should be exceedling rare.
> Fix duplicate transactions from router

- src/be_cli_backfill.erl
- src/be_db_backfill.erl
Adds a `backfill reversed_receipts_paths` command to go through given block ranges, check for reversed poc paths in receipts and fix them in the database. 
This should only apply to block ranges where etl 1.1.44 was active as it was fixed in 1.1.45
> backfill reversed receipt paths

- migrations/1599584290-state_channel_owner.sql
Adds an on conflict handler for the `state_channel_owner`` migrations to assist with mismanaged migrations.
> Add conflict handlers for mismanaged migrations

- src/be_db_geocoder.erl
Misusing async hackney results caused an error for geocodes with a large
json response (more than one chunk). This is now fixed
> Fixes geocode crash for large response

- migrations/1606096996-gateway_first_timestamp.sql
- src/be_db_gateway.erl
`first_timestamp` is the timestamp when the gateway was first inserted into the chain (i.e. the timestamp associated with `first_block`).
Part of https://github.com/helium/blockchain-http/issues/132
> Add first_timestamp to gateway_inventory

- migrations/1609078980-gateway_listen_addrs.sql
- src/be_db_gateway_status.erl
Adds a jsonb `listen_addrs` column which is updated as part of the gateway status update cycle
> Add listen_addrs to gateway_status

- config/sys.config
- migrations/1609338698-packets.sql
- src/be_db_follower.erl
- src/be_db_packet.erl
This extracts the packet/dc counts from state_channel_close transactions (similar to how rewards are extracted from rewards transactions) to allow for queries around data transfers.
> Adds packet tracking

- migrations/1609356128-jsonb_merge_agg.sql
Adds an aggregator to union multiple jsonb maps together. This is used, for example, to merge witness maps
> Adds jsonb_merge_agg aggregator

- migrations/1612220889-reward_brin_idx.sql
1. Drops the block index since it’s already part of the pkey compound key
2. Adds a BRIN time index to make time bucketed reward sums possible
> Tweaks reward indices

- migrations/1612479163-oui_routing_fixup.sql
- src/be_db_txn_actor.erl
* This fixes the early ouis to be the actual oui transaction value (which needs to be the _current_ oui not the requested/assigned one.
* It also adds an payer actor for the owner of routing_v1 changes
Fixes #125
> Fix up wrongly numbered ouis and routing actors

- migrations/1612480010-ouis.sql
- src/be_db_backfill.erl
oui inventory was representing incorrect routers as owners since routing_v1 transactions can have the “owner” be any of the currently valid router addresses.
The backfill fixes up the owner address for ouis, and adds the router addresses back in.
The fixed up migration will help newly migrated folks to get the same effect
> Fix up oui_inventory

- Makefile
- README.md
Related to `.env` -> `.env.$PROFILE` switch from https://github.com/helium/blockchain-etl/commit/9059f18168d227e6e02e66607a9a54bbb4e4c27c
This felt simpler than refactoring code and adding conditionals, but it also means that existing installs using `.env` will still be broken if they update
> Use .env.dev by default, and allow PROFILE ENV var

- Makefile
- README.md
Slightly more backwards-compatible, and makes more logical sense to me
Arguably could add some checks to favor ".env.dev" over ".env" if it exists? But this is already getting fancy
> Switch back to .env instead of .env.dev

- src/be_db_reward.erl
overages in v2 crashes when it goes into collect v2, since it's an integer.  just ignore it, we can get it from the json later if we need it.
> ignore overages, since it doesn't collect like the others

- src/be_cli_backfill.erl
- src/be_db_backfill.erl
- src/be_db_txn_actor.erl
This fixes an inadvertent removal of reward_gateway actors for rewards_v1 transactions which would cause api hotspot activity to not see the rewards transactions.
The backfill is provided to backfill actors for block ranges.. Run this backwards from the current height in about 100 block decrements until the output  returns 0 updated
> Fix missing reward_gateway actors

- migrations/1617917369-rewards_v2_activity_filter.sql
Rewards activity for rewards_v2 was not filtering the rewards entries for the given actor, resulting in giant API responses for activity.
> Filter rewards_v2 activity

- src/be_db_pending_txn.erl
Since the txn_mgr will retry transactions across elections, the transaction could clear while the txn mgr is sending retries which would then come back as failures.
This would cause the  pending_txn to be marked as failed after it had cleared.
This patch ensures that a failed status is only set if the current status is not already cleared
> Only set failed status if current status is not cleared

- src/be_db_gateway.erl
Large integers are not well supported by JS which makes first_time and recent_time fail or warn loudly in some JS packages.
This changes these to strings so that JS implementations can choose to parse this with (for example) a bigint library, or ignorre it safely
Fixes #163
> Changes two ms accuracy witness timestamps to strings

- migrations/1620768447-gateway_location_hex.sql
- scripts/extensions/backfill
- src/be_cli_backfill.erl
- src/be_db_backfill.erl
- src/be_db_gateway.erl
This adds a location_hex column to gateways which allows for gateways to be grouped by a hardcoded h3 resolution (8 today). 
This is the etl side to support: https://github.com/helium/blockchain-http/issues/255
> Add location_hex for res (8) based hex lookups

- src/be_db_backfill.erl
- src/be_db_gateway.erl
instead of using get_parent
Fixes #189
> Fixes location_hex to be computed from lat/lon

- src/be_db_validator.erl
since we have not added the penalty vars to the mainnet chain, this code was failing.  we ignore the failure in this PR and return safe defaults.
> ignore when penalty calculation fails with safe defaults

- config/sys.config
- src/be_db_gateway_status.erl
- src/be_db_validator_status.erl
* Orders null entries the same way selection is done
* Increase the number of connections to the db pool to ease up pool pressure
> Update gateway/validator status null entries

- migrations/1628075186-state_channel_close_v1_activity_coalesce.sql
For state channel owners the activity filtered summaries would be null, causing the complete result to be null.
This coalesces the summaries to an empty array which correctly represents the filtered activity summaries for the owner/closer of the state channel
> Coalesce state_channel_close summaries

- migrations/1628163172-location_city_search_word_order.sql
Word ordering affects the text index so keep the word ordering in location_city_words the same as the order of words in the location columns
> Fix city search word order

- config/sys.config
- src/be_db_account.erl
- src/be_db_follower.erl
- src/be_db_reward.erl
- src/be_db_txn_actor.erl
This makes the terrible assumption that there are only two users of rewards metadata.
Using an ets table as a way to hand of a rewards table between to disjoint pieces of code is terrible but maybe it'll help
> Hack to one time memoize reward metadata

- src/be_db_dc_burn.erl
When a state channel is disputed the same txn hash and actors may happen. This will cause dc burns to fail inserting.
This hack ignores dc burns duplicates to avoid etl falling over
> Ignore disputed state channel txn

- src/be_cli_backfill.erl
- src/be_db_backfill.erl
- src/be_db_geocoder.erl
Only the first address components of the result list was previously searched for geocode fields.
This change has it search all address component entries in order for the first one that has a result for both long _and_ short name.
After deploying this delete all rows in the locations table with a null short/long entry by running `backfill gateway_location_clear_nulls`. The geocoder will re-geocode the missing rows. 
Fixes #235
> Extend the address component search to all entries

- src/be_cli_backfill.erl
- src/be_db_backfill.erl
- src/be_db_gateway.erl
This switches to using h3:parent to move from res12 to res8 to match what the PoC core does with targeting.
**NOTE** This change _also_ requires the `gateway_location_hex` to be re-run, which will take about 5 minutes in the background for 200k hotspots
Fixes #191
> Use parent h3 instead of to/from_geo

- src/be_cli_backfill.erl
- src/be_db_backfill.erl
- src/be_db_gateway.erl
Only insert reward scale when `mode` for gateway is `full`.
TODO:
> Only insert scale for full gws

- config/sys.config
- rebar.config
- rebar.lock
This upgrades core to 2021.11.21.1 to work add some more critical performance improvements under heavy transaction load
> bump core and assumed valid block hash

- Dockerfile
- config/sys.config
Optimizing the docker build to pre-compile dependencies in a separate stage so they can be cached in a separate layer so long as there have been no changes to the rebar.config/rebar.lock files.
Also bumps the latest release of blockchain-core that patches a peer gossip bug related to allowance of rfc1918 addresses.
> updating dependencies and optimizing docker build

- .dockerignore
Adding dockerignore file to prevent locally compiled builds of the app from populating build images when the source directory is copied into the container for compilation.
> Adding dockerignore file

- migrations/1637295492-rewards_type.sql
- src/be_db_reward.erl
This removes the rewards_pkey constraint since reward_type adds duplicate account/gateway/block constraint violations. There are other indices for gateway/account so this should hopefully not affect rewards query performance
> Add reward type to rewards schema

- src/be_db_txn_actor.erl
Since the insertion ignores conflicts, fewer than the desired rows may be stored
> Ignore actual returned rows

- deb/blockchain-etl.service
Problem to solve: Currently systemd will attempt to start the service over and over, even if it keeps crashing. We would like for it to eventually give up if it goes into a failed state.
Solution: Limit restart attempts to 3 times, each one lasting 15 seconds apart, for up to 60 seconds. If the service is still not running by then, enter the failed state and do not attempt to restart until a human does something.
> Attempt to restart the service 3 times

- src/be_db_block.erl
For immediate usage. #311 can be adopted too.
> Stop storing uncompressed snapshots

- src/be_db_stats.erl
locations.location is a not null field, gateway_inventory.location is a nullable field, so query makes more sense (and is faster) when where is `g.location is not null`
> fix cities and countries location not null where

- src/be_db_gateway_status.erl
remove coalesce so indexes are used, updated_at is already not null + default now() so the coalesce to default to_timestamp(0) isn't needed
> speed up S_STATUS_UNKNOWN_LIST

- migrations/1650412999-account_owner_first_block.sql
- src/be_db_account.erl
Account roles were failing to include transactions that affected the account “activity“but where not payment related. add_gateway, transfer_hotspot_v2 to a new account address were primary victims of this.
This adds the “owner” actor as a trigger for a new account row insert which will fix it for new accounts.
It also adds a migration that fixes up any account’s first_block fields,  that have “owner” actor entries before the first payment activity.
Fixes https://github.com/helium/blockchain-http/issues/412
Fixes https://github.com/helium/blockchain-http/issues/421
> Fixes first_block for accounts

- migrations/1650926462-gateway_last_block.sql
- src/be_db_gateway.erl
- src/be_db_gateway_status.erl
- src/be_peer_status.erl
The blockchain-http repo already had a workaround in place to return a hotpot status as online if the hotspots had any activity on chain.
This worked but would then not reflect in generated extracts or in city counts.
This PR updates the gateway_status.online column based on the same logic.. i.e.: A hotspot is _online_ if it has _any_ on chain activity in the last 36 hours of blocks (2160 blocks).
A side effect of this PR is that ARPs are no longer sent since we’re no longer interested in using the hotspot gossiped height as an indication of how far along it is. This is not a big deal _except_ that listen_addresses are no longer updated as frequently which will no longer matter with light hotspots around the corner
> Changes the online storage to match http

- README.md
With tag: 1.1.151, instances running on OTP 22 and 23 got stucked. OTP 24 is required from now on.
> Updating README for erlang/OTP version (22 -> 24)

- src/be_db_pending_txn.erl
be_txn:to_json requires use of ledger for a number of txns to add more relevant context. During txn submission that context is not relevant since the txn hasn’t been accepted by the chain yet. Use the basic blockchain_txn:to_json instead
> Avoid use of be_txn:to_json

- CONTRIBUTING.md
Currently the docs are pointing to the [helium/libp2p-peerbook](https://github.com/helium/libp2p-peerbook) repo instead of here.
> Fix the CONTRIBUTING.md file pointing to the wrong repo
